default_stages: [commit, push]
default_language_version:
  python: python3.10
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-ast
    -   id: debug-statements
    -   id: trailing-whitespace
    -   id: mixed-line-ending
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-case-conflict
    -   id: check-added-large-files
    -   id: detect-private-key
    -   id: check-merge-conflict

  - repo: https://github.com/psf/black
    rev: 21.8b0
    hooks:
    - id: black
      args: [
        --line-length=80,
        --target-version=py39
      ]
      exclude: ^(venv/|docs/)
      types: ['python']

  - repo: https://github.com/asottile/blacken-docs
    rev: v1.11.0
    hooks:
    -   id: blacken-docs
        additional_dependencies: [black==21.8b0]

  -  repo: https://github.com/asottile/pyupgrade
     rev: v2.7.2
     hooks:
      - id: pyupgrade
