DATABASE_URI:
TORTOISE_APP_NAME: My Wonderful Bot
DISCORD_ID:
DISCORD_TOKEN:

DEFAULT_REDIS_PATH:
REDIS_URI: redis://localhost:6379


OSU_API_V1_KEY:
OSU_API_V2_CLIENT_ID:
OSU_API_V2_CLIENT_SECRET:
OSU_API_V2_CLIENT_CALLBACK_URL: http://localhost:727 #  ඞ

BITLY_API_TOKEN:

DEFAULT_PREFIX: "-"
BOT_VERSION: "1.0.0"

RPC_ENABLED:
RPC_LARGE_IMAGE:
RPC_LARGE_TEXT:
RPC_SMALL_IMAGE:
RPC_SMALL_TEXT:
