DATABASE_URI:
DISCORD_ID:
DISCORD_TOKEN:

DEFAULT_REDIS_PATH:
REDIS_URI: redis://localhost:6379


OSU_API_V1_KEY:
OSU_API_V2_CLIENT_ID:
OSU_API_V2_CLIENT_SECRET:
OSU_API_V2_CLIENT_CALLBACK_URL: http://localhost:727 #  ඞ
