# -- Project information

site_name: Mai
site_author: Ghoul
site_description: A Discord Bot That Transcends Normality

# -- Copyright
copyright: "Copyright &copy; 2021 Ghoul"

# -- Repository
repo_name: Mai
repo_url: https://github.com/xFGhoul/Mai
edit_uri: ""


theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github

  palette:
    - scheme: default

      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate

      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"

      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"

      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

  features:
    - navigation.instant
    - navigation.tabs

    - search.highlight
    - search.share
    - search.suggest

# -- Extensions
markdown_extensions:
  - abbr
  - attr_list
  - md_in_html


  - admonition
  - codehilite
  - footnotes
  - tables


  - pymdownx.keys
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.tabbed
  - pymdownx.details
  - pymdownx.smartsymbols
  - pymdownx.betterem
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.highlight
  - pymdownx.inlinehilite

  - pymdownx.tasklist:
      custom_checkbox: true

  - toc:
      permalink: true
      separator: "_"

# -- Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
      lang:
        - en


# -- Extras
extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/xFGhoul"
    - icon: "fontawesome/brands/twitter"
      link: "https://twitter.com/xghouldev"
